[package]
name = "linear_model"
version = "0.1.0"
edition = "2021"

[lib]
name = "linear_model"
crate-type = ["cdylib"]
path = "src/linear_model.rs"

[dependencies]
ndarray = "0.15"
rand = "0.8"